name: Build and Deploy with Docker Compose on Push

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch (or any branch you prefer)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (required for Docker Compose)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Set up Docker Compose
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Step 5: Build and push images using Docker Compose
      - name: Build and push with Docker Compose
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

      # Step 6: SSH to EC2 instance and create directory
      - name: SSH to Ubuntu Instance and create directory
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.UBUNTU_HOST }}
          username: ${{ secrets.UBUNTU_USER }}
          key: ${{ secrets.UBUNTU_SSH_KEY }}
          port: 22
          script: |
            mkdir -p ~/hello\ word

# name: Create Directory on Push

# on:
#   push:
#     branches:
#       - main # or any branch you want to trigger on push

# jobs:
#   create-dir:
#     runs-on: ubuntu-latest
    
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2
        
#       - name: SSH to Ubuntu Instance and create directory
#         uses: appleboy/ssh-action@v0.1.5
#         with:
#           host: ${{ secrets.UBUNTU_HOST }}
#           username: ${{ secrets.UBUNTU_USER }}
#           key: ${{ secrets.UBUNTU_SSH_KEY }}
#           port: 22
#           script: |
#             mkdir -p ~/hello\ word
