name: Build and Deploy Docker App to EC2

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Add this secret in GitHub Secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Add this secret in GitHub Secrets

    - name: Build Docker image
      run: |
        docker build -t myapp:${{ github.sha }} .
      
    - name: Push Docker image to Docker Hub
      run: |
        docker push myapp:${{ github.sha }}

    - name: SSH to EC2 and deploy Docker container
      uses: appleboy/ssh-action@v0.1.0
      with:
        host: ${{ secrets.EC2_HOST }}  # EC2 public IP address
        username: ubuntu  # Change based on your EC2 instance's user
        key: ${{ secrets.EC2_SSH_KEY }}  # Your private SSH key secret
        port: 22
        script: |
          cd /home/ubuntu/app-directory  # Adjust to your app directory on EC2
          docker pull myapp:${{ github.sha }}
          docker-compose down  # Optional, stop previous containers
          docker-compose up -d  # Or simply run the docker run command to start the container
