name: Build and Deploy App with Docker Compose

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Add this secret in GitHub Secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Add this secret in GitHub Secrets

    - name: Build Docker images with Docker Compose
      run: |
        # Use docker-compose to build the images
        docker-compose -f docker-compose.yml build

    - name: Tag Docker images
      run: |
        # Tag the images based on the commit SHA for versioning
        docker tag myapp:latest harish130615/sample:${{ github.sha }}  # Replace 'myapp' with your service name
        # Alternatively, tag all images defined in your docker-compose.yml
        docker-compose -f docker-compose.yml images | awk '{print $1}' | xargs -I {} docker tag {}:{} harish130615/sample:${{ github.sha }}

    - name: Push Docker images to Docker Hub
      run: |
        # Push all images defined in your docker-compose.yml to Docker Hub
        docker-compose -f docker-compose.yml push

    - name: SSH to EC2 and deploy Docker container
      uses: appleboy/ssh-action@v0.1.0
      with:
        host: ${{ secrets.EC2_HOST }}  # EC2 public IP address
        username: ubuntu  # EC2 user (typically 'ubuntu' for Ubuntu-based instances)
        key: ${{ secrets.EC2_SSH_KEY }}  # SSH private key to access EC2
        port: 22
        script: |
          cd /home/ubuntu/app-directory  # Adjust to your app directory on EC2
          docker-compose pull  # Pull the latest images from Docker Hub
          docker-compose up -d  # Recreate and start containers in detached mode
